/**
 * Generated API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.rest.client.api;

import com.example.rest.client.models.Drink;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.MediaType;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

/**
 * Generated API
 *
 * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */

@RegisterRestClient(baseUri = "http://localhost:9080/rest-service")
@RegisterProvider(ApiExceptionMapper.class)
@Path("/")
public interface DefaultApi  {

    @GET
    @Path("/api/cafe")
    @Produces({ "application/json" })
    public List<Drink> apiCafeGet() throws ApiException, ProcessingException;

    @POST
    @Path("/api/cafe")
    public void apiCafePost(@QueryParam("name") String name, @QueryParam("cost") Double cost) throws ApiException, ProcessingException;

    @GET
    @Path("/api/cafe/size")
    @Produces({ "*/*" })
    public Integer apiCafeSizeGet() throws ApiException, ProcessingException;
}

